### ISSUE TITLE
安装后无法使用

### ISSUE THREAD

**Issue by gotask** [tanghuibo/qrcode-chrome-plug-in#1]
提示，该扩展程序未列在 Chrome 网上应用店中，并可能是在您不知情的情况下添加的。

**Comment by tanghuibo** [comment]
试一下这个: https://jingyan.baidu.com/article/ceb9fb108bad968cad2ba0f0.html

**Comment by tanghuibo** [comment]
可能时浏览器的安全策略导致的，我暂时没有遇到过
